'use strict';

var sentences = [
    "A ambição cerra o coração.",
    "A apressada pergunta, vagarosa resposta.",
    "A ave de rapina não canta.",
    "A barriga não tem fiador.",
    "A boa mão, do Rocim faz cavalo; e a ruim, do Cavalo faz Rocim.",
    "A boca do ambicioso só se fecha com terra da sepultura.",
    "A boda e a baptizado não vás sem ser convidado.",
    "A cada Bacorinho, vem seu S. Martinho (11/11).",
    "A cada boca uma sopa.",
    "A cadela, com pressa, pariu os cachorros cegos.",
    "A campo fraco, Lavrador forte.",
    "A casamento e baptizado, não vás sem ser convidado.",
    "A cavalo dado não se olha o dente.",
    "A chuva de S. João (24/6), bebe o Vinho e come o Pão.",
    "A chuva e o frio, metem a Lebre a caminho.",
    "A conselho amigo, não feches o postigo.",
    "A culpa morreu solteira.",
    "A desgraça não marca encontro.",
    "A encomenda é igual ao cabaz.",
    "A espada e o anel, segundo a mão em que estiverem.",
    "A falta do amigo há-de-se conhecer mas não aborrecer.",
    "A fama longe soa. E mais depressa a má que a boa.",
    "A fome é a melhor cozinheira.",
    "A fome é boa mostarda.",
    "A fome é o melhor tempero.",
    "A fome faz sair o lobo do mato.",
    "A galinha da vizinha é sempre melhor que a minha.",
    "A ganhar se perde e a perder se ganha.",
    "A gosto danado, o doce é amargo.",
    "A ignorância e o vento são do maior atrevimento.",
    "A justiça tarda mas não falha.",
    "A Laranja, de manhã é Ouro, de tarde é Prata, e à noite mata.",
    "A lei é dura, mas é para se cumprir.",
    "A melhor Cozinheira, é a azeiteira.",
    "A Morte abre a porta da Fama e fecha a da Inveja.",
    "A mulher, sem pôr o pé faz pegada.",
    "A necessidade aguça o engenho.",
    "A necessidade não tem lei.",
    "A noite é boa conselheira.",
    "A nuvem passa, mas a chuva fica.",
    "A ocasião faz o ladrão.",
    "A ociosidade é mãe de todos os vícios.",
    "A palavra é de prata e o silêncio é de ouro.",
    "A pedra e a palavra, não se recolhe depois de deitada.",
    "A Pescada de Janeiro, vale um carneiro.",
    "A pintura e a peleja, de longe se veja.",
    "A pobreza não é vileza, nem a riqueza nobreza.",
    "A preguiça é a mãe de todos os vícios.",
    "A preguiça morre à sede, andando a boiar.",
    "A pressa é inimiga da perfeição.",
    "A primeira, qualquer cai. À segunda cai quem quer.",
    "A quem do seu foi mau despenseiro, não fies o teu dinheiro.",
    "A quem tudo quer saber, nada se lhe diz.",
    "A razão e a verdade fogem quando ouvem disputas.",
    "A rir se corrigem os costumes.",
    "A roupa suja lava-se em casa.",
    "A união faz a força.",
    "A vaidade é o espelho dos tolos.",
    "A valentia com os fracos, só cobardia revela.",
    "A ventre farto o mel amarga.",
    "A verdade é como o azeite: Vem sempre ao de cima.",
    "A vozes loucas, orelhas moucas.",
    "Abril frio e molhado, enche o celeiro e farta o gado.",
    "Abril, Abril, está cheio o covil.",
    "Agosto tem a culpa, e Setembro leva a fruta.",
    "Água de Fevereiro, mata o Onzeneiro.",
    "Água de Julho, no rio não faz barulho.",
    "Água detida é má para a bebida.",
    "Água e vento são meio sustento.",
    "Água mole em pedra dura, tando dá até que fura.",
    "Águas da Ascensão, das palhas fazem Grão.",
    "Águas passadas não movem Moinhos.",
    "Águas verdadeiras, por S. Mateus as primeiras.",
    "Aí por Sant'ana, limpa a pragana.",
    "Ainda que mude a pele a Raposa, seu natural desponja.",
    "Albarda-se o burro à vontade do dono.",
    "Almoço cedo, faz carne e sebo; almoço tarde, nem sebo nem carne.",
    "Alto mar e não de vento, não promete seguro o tempo.",
    "Amigo deligente, é melhor que parente.",
    "Amigo disfarçado, inimigo dobrado.",
    "Amigo que não presta e faca que não corta: que se percam, pouco importa.",
    "Amigo verdadeiro vale mais do que dinheiro.",
    "Amigo, vinho e azeite o mais antigo.",
    "Amigos, amigos, negócios à parte.",
    "Amor com amor se paga.",
    "Amor de pais não há jamais.",
    "Amor querido, amor batido.",
    "Amores arrufados, amores dobrados.",
    "Ande o frio por onde andar, no Natal cá vem parar.",
    "Ande por onde andar o Verão, há-de vir no S. João.",
    "Ano de nevão, ano de pão.",
    "Ano de neve, paga o que deve.",
    "Antes caia do cú do que do alforge.",
    "Antes cegues que mal vejas.",
    "Antes martelo que bigorna.",
    "Antes mau ano que mau vizinho.",
    "Antes minha face com fome amarela, que vergonha nela.",
    "Antes que te cases, vê o que fazes.",
    "Antes quebrar que torcer.",
    "Antes quero Asno que me leve, que Cavalo que me derrube.",
    "Ao arrendar cantar e ao pagar chorar.",
    "Ao bebado e ao tolo, dá-se o caminho todo.",
    "Ao bom amigo, com teu pão e teu vinho.",
    "Ao bom pagador não dói o penhor.",
    "Ao Diabo e à mulher nunca falta que fazer.",
    "Ao Fevereiro e ao rapaz, perdoa tudo quanto faz.",
    "Ao homem de esforço a fortuna lhe põe ombro.",
    "Ao homem ousado a fortuna dá a mão.",
    "Ao menino e ao borracho põe Deus a mão por baixo.",
    "Ao pé do pano é que se talha a obra.",
    "Ao quinto dia verás que mês terás.",
    "Ao rico mil amigos se deparam, ao pobre seus irmãos o desamparam.",
    "Ao rico não devas e ao pobre não peças.",
    "Ao rico não faltes, ao pobre não prometas.",
    "Apanha com o cajado quem se mete onde não é chamado.",
    "Apanha-se mais depressa um mentiroso do que um coxo.",
    "Apanham-se mais moscas com mel do que com fel.",
    "Apressado come cru.",
    "Aproveite Fevereiro quem folgou em Janeiro.",
    "Aquele que me tira do perigo, é meu amigo.",
    "Aquilo que sabe bem, ou faz mal ou é pecado.",
    "Arco de teixo duro de armar e fraco para disparar.",
    "Arco sempre armado, ou frouxo ou quebrado.",
    "Arrenda a vinha e o pomar se os queres desgraçar.",
    "As aparências iludem.",
    "As boas contas fazem os bons amigos.",
    "As cadelas apressadas parem cães tortos.",
    "As favas, Maio as dá, Maio as leva.",
    "As obras falam, as palavras calam.",
    "As palavras são como as cerejas, vêm umas atrás das outras.",
    "As palavras voam, a escrita fica.",
    "As paredes têm ouvidos.",
    "As sopas e os amores, os primeiros são os melhores.",
    "Às vezes não se respeita o burro, mas a argola a que ele está amarrado.",
    "Assim como vires o tempo de Santa Luzia ao Natal, assim estará o ano mês a mês até final.",
    "Até ao lavar dos cestos é vindima.",
    "Até ao Natal um saltinho de pardal.",
    "Até S. Pedro abre rego e fecha rego.",
    "Até S. Pedro tem a vinha medo.",
    "Atrás de mim virá, quem de mim bem dirá.",
    "Ave que canta demais não sabe fazer o ninho.",
    "Ave só não faz ninho.",
    "Azeite de cima, mel do fundo e vinho do meio.",

    "A ambição cerra o coração.",
    "A pressa é inimiga da perfeição.",
    "Águas passadas não movem moinhos.",
    "Amigo não empata amigo.",
    "Amigos amigos negócios à parte.",
    "Água mole em pedra dura, tanto dá até que fura.",
    "A união faz a força.",
    "A ocasião faz o ladrão.",
    "A ignorância é a mãe de todas as doenças.",
    "Amigos dos meus amigos, meus amigos são.",
    "A cavalo dado não se olha a dente.",
    "Azeite de cima, mel do meio e vinho do fundo, não enganam o mundo.",
    "Antes só do que mal acompanhado.",
    "A pobre não prometas e a rico não devas.",
    "A mulher e a sardinha, querem-se da mais pequenina.",
    "A galinha que canta como galo corta-lhe o gargalo.",
    "A boda e a baptizado, não vás sem ser convidado.",
    "A galinha do vizinho é sempre melhor que a minha.",
    "A laranja de manhã é ouro, à tarde é prata e à noite mata.",
    "A necessidade aguça o engenho.",
    "A noite é boa conselheira.",
    "A ocasião faz o ladrão.",
    "A preguiça é mãe de todos os vícios.",
    "A palavra é de prata e o silêncio é de ouro.",
    "A palavras (ocas|loucas) orelhas moucas.",
    "A pensar morreu um burro.",
    "A roupa suja lava-se em casa.",
    "Antes só que mal acompanhado.",
    "Antes tarde do que nunca.",
    "Ao rico mil amigos se deparam, ao pobre seus irmãos o desamparam.",
    "Ao rico não faltes, ao pobre não prometas.",
    "As palavras voam, a escrita fica.",
    "As (palavras ou conversa ...) são como as cerejas, vêm umas atrás das outras.",
    "Até ao lavar dos cestos é vindima.",
    "Água e vento são meio sustento.",
    "Águas passadas não movem moinhos.",
    "Boi velho gosta de erva tenra.",
    "Boca que apetece, coração que padece.",
    "Baleias no canal, terás temporal.",
    "Boa fama granjeia quem não diz mal da vida alheia.",
    "Boa romaria faz, quem em casa fica em paz.",
    "Boda molhada, boda abençoada.",
    "Burro velho não aprende línguas.",
    "Burro velho não tem andadura e se tem pouco dura.",
    "Cada cabeça sua sentença.",
    "Chuva de São João, tira vinho e não dá pão.",
    "Casa roubada, trancas à porta.",
    "Casarás e amansarás.",
    "Criou a fama, deite-se na cama.",
    "Cada qual com seu igual.",
    "Cada ovelha com sua parelha.",
    "Cada macaco no seu galho.",
    "Casa de ferreiro, espeto de pau.",
    "Casamento, apartamento.",
    "Cada qual é para o que nasce.",
    "Cão que ladra não morde.",
    "Cada qual sabe onde lhe aperta o sapato.",
    "Com vinagre não se apanham moscas.",
    "Coma para viver, não viva para comer.",
    "Com o direito do teu lado nunca receies dar brado.",
    "Candeia que vai à frente alumia duas vezes.",
    "Casa de esquina, ou morte ou ruína.",
    "Cada panela tem a sua tampa.",
    "Cada um sabe as linhas com se cose.",
    "Cada um sabe de si e Deus sabe de todos.",
    "Casa onde entra o sol não entra o médico.",
    "Cautela e caldos de galinha nunca fizeram mal a ninguém.",
    "Cesteiro que faz um cesto faz um cento,se lhe derem verga e tempo.",
    "Com a verdade me enganas.",
    "Com papas e bolos se enganam os tolos.",
    "Comer e o coçar o mal é começar.",
    "Devagar se vai ao longe.",
    "Depois de fartos, não faltam pratos.",
    "De noite todos os gatos são pardos.",
    "Desconfia do homem que não fala e do cão que não ladra.",
    "De Espanha nem bom vento nem bom casamento.",
    "De pequenino se torce o pepino.",
    "De grão a grão enche a galinha o paparrão.",
    "Devagar se vai ao longe.",
    "De médico e de louco, todos temos um pouco.",
    "Diz-me com quem andas, dir-te-ei quem és.",
    "Diz o roto ao nu 'Porque não te vestes tu.",
    "Depressa e bem não há quem.",
    "Deitar cedo e cedo erguer, dá saúde e faz crescer.",
    "Depois da tempestade vem a bonança.",
    "Da mão à boca vai-se a sopa.",
    "Deus ajuda, quem cedo madruga.",
    "Dos fracos não reza a história.",
    "Em casa de ferreiro, espeto de pau.",
    "Enquanto há vida, há esperança.",
    "Entre marido e mulher, não se mete a colher.",
    "Em terra de cego quem tem olho é rei.",
    "Erva daninha a geada não mata.",
    "Em casa onde não há pão, todos ralham e ninguém tem razão.",
    "Em tempo de guerra não se limpam armas.",
    "Falar é prata, calar é ouro.",
    "Filho de peixe, sabe nadar.",
    "Gaivotas em terra, tempestade no mar.",
    "Guardado está o bocado para quem o há de comer.",
    "Galinha de campo não quer capoeira.",
    "Gato escaldado de água fria tem medo.",
    "Guarda o que comer, não guardes o que fazer.",
    "Homem prevenido vale por dois.",
    "Há males que vêm por bem.",
    "Homem pequenino ou velhaco ou dançarino.",
    "Ignorante é aquele que sabe e se faz de tonto.",
    "Junta-te aos bons, serás como eles, junta-te aos maus, serás pior do que eles.",
    "Lua deitada, marinheiro de pé.",
    "Lua nova trovejada, 30 dias é molhada.",
    "Ladrão que rouba a ladrão, tem cem anos de perdão.",
    "Longe da vista, longe do coração.",
    "Mais vale um pássaro na mão, do que dois a voar.",
    "Mal por mal, antes na cadeia do que no hospital.",
    "Manda quem pode, obedece quem deve.",
    "Mãos frias, coração quente.",
    "Mais vale ser rabo de pescada que cabeça de sardinha.",
    "Mais vale cair em graça do que ser engraçado.",
    "Mais depressa se apanha um mentiroso que um coxo.",
    "Mais vale perder um minuto na vida do que a vida num minuto.",
    "Madruga e verás trabalha e terás.",
    "Mais vale um pé no travão que dois no caixão.",
    "Mais vale uma palavra antes que duas depois.",
    "Mais vale prevenir que remediar.",
    "Morreu o bicho, acabou-se a peçonha.",
    "Muita parra pouca uva.",
    "Muito alcança quem não se cansa.",
    "Muito come o tolo mas mais tolo é quem lhe dá.",
    "Muito riso pouco siso.",
    "Muitos cozinheiros estragam a sopa.",
    "Não há mal que sempre dure, nem bem que não se acabe.",
    "Nuvem baixa sol que racha.",
    "Não peças a quem pediu nem sirvas a quem serviu.",
    "Nem tudo o que reluz é ouro.",
    "Não há bela sem senão.",
    "Nem tanto ao mar nem tanto à terra.",
    "Não há fome que não dê em fartura.",
    "Não vendas a pele do urso antes de o matar.",
    "Não há duas sem três.",
    "No meio é que está a virtude.",
    "No melhor pano cai a nódoa.",
    "Nem contas com parentes nem dívidas com ausentes.",
    "Nem oito nem oitenta.",
    "Nem tudo o que vem à rede é peixe.",
    "No aperto e no perigo se conhece o amigo.",
    "No poupar é que está o ganho.",
    "Não dá quem tem, dá quem quer bem.",
    "Não há sábado sem sol, domingo sem missa nem segunda sem preguiça.",
    "O saber não ocupa lugar.",
    "Os cães ladram e caravana passa.",
    "O seguro morreu de velho.",
    "O prometido é devido.",
    "O que arde cura o que coça sara e o que aperta segura.",
    "O segredo é a alma do negócio.",
    "O bom filho à casa retorna.",
    "O casamento e a mortalha no céu se talha.",
    "O futuro a Deus pertence.",
    "O homem põe e Deus dispõe.",
    "O que não tem remédio remediado está.",
    "O saber não ocupa lugar.",
    "O seguro morreu de velho.",
    "O seu a seu dono.",
    "O sol quando nasce é para todos.",
    "O óptimo é inimigo do bom.",
    "Os amigos são para as ocasiões.",
    "Os opostos atraem-se.",
    "Os homens não se medem aos palmos.",
    "Para frente é que se anda.",
    "Pau que nasce torto jamais se endireita.",
    "Pedra que rola não cria limo.",
    "Para bom entendedor meia palavra basta.",
    "Por fora bela viola, por dentro pão bolorento.",
    "Para baixo todos os santos ajudam.",
    "Por morrer uma andorinha não acaba a primavera.",
    "Patrão fora, dia santo na loja.",
    "Para grandes males, grandes remédios.",
    "Preso por ter cão, preso por não ter.",
    "Paga o justo pelo pecador.",
    "Para morrer basta estar vivo.",
    "Para quem é, bacalhau basta.",
    "Passarinhos e pardais,não são todos iguais.",
    "Peixe não puxa carroça.",
    "Pela boca morre o peixe.",
    "Perde-se o velho por não poder e o novo por não saber.",
    "Pimenta no cu dos outros para mim é refresco.",
    "Presunção e água benta, cada qual toma a que quer.",
    "Quando a esmola é grande o santo desconfia.",
    "Quem espera sempre alcança.",
    "Quando um não quer, dois não discutem.",
    "Quem tem telhados de vidro não atira pedras.",
    "Quem vai à guerra dá e leva.",
    "Quem parte e reparte e não fica com a melhor parte, ou é tolo ou não tem arte.",
    "Quem sai aos seus não degenera.",
    "Quem vai ao ar perde o lugar e quem vai ao vento perde o assento.",
    "Quem semeia ventos colhe tempestades.",
    "Quem vê caras não vê corações.",
    "Quem não aparece, esquece; mas quem muito aparece, tanto lembra que aborrece.",
    "Quem casa quer casa.",
    "Quem come e guarda, duas vezes põe a mesa.",
    "Quem com ferros mata, com ferros morre.",
    "Quem corre por gosto não cansa.",
    "Quem muito fala pouco acerta.",
    "Quem quer festa, sua-lhe a testa.",
    "Quem dá e torna a tirar ao inferno vai parar.",
    "Quem dá aos pobres empresta a Deus.",
    "Quem cala consente.",
    "Quem mais jura é quem mais mente.",
    "Quem não tem cão, caça com gato.",
    "Quem diz as verdades, perde as amizades.",
    "Quem se mete em atalhos não se livra de trabalhos.",
    "Quem não deve não teme.",
    "Quem avisa amigo é.",
    "Quem ri por último ri melhor.",
    "Quando um burro fala, o outro abaixa a orelha.",
    "Quanto mais te agachas, mais te põem o pé em cima.",
    "Quem conta um conto acrescenta-lhe um ponto.",
    "Quem diz o que quer, ouve o que não quer.",
    "Quem não chora não mama.",
    "Quem desdenha quer comprar.",
    "Quem canta seus males espanta.",
    "Quem feio ama, bonito lhe parece.",
    "Quem não arrisca não petisca.",
    "Quem tem boca vai a Roma.",
    "Quando o mar bate na rocha quem se lixa é o mexilhão.",
    "Quando um cai todos o pisam.",
    "Quanto mais depressa mais devagar.",
    "Quem entra na chuva é pra se molhar.",
    "Quem boa cama fizer nela se deitará.",
    "Quem brinca com o fogo queima-se.",
    "Quem cala consente.",
    "Quem canta seus males espanta.",
    "Quem comeu a carne que roa os ossos.",
    "Quem está no convento é que sabe o que lhe vai dentro.",
    "Quem muito escolhe pouco acerta.",
    "Quem nada não se afoga.",
    "Quem nasceu para a forca não morre afogado.",
    "Quem não quer ser lobo não lhe vista a pele.",
    "Quem não sabe é como quem não vê.",
    "Quem não tem dinheiro não tem vícios.",
    "Quem não tem panos não arma tendas.",
    "Quem não trabuca não manduca.",
    "Quem o alheio veste, na praça o despe.",
    "Quem o seu cão quer matar chama-lhe raivoso.",
    "Quem paga adiantado é mal servido.",
    "Quem parte velho paga novo.",
    "Quem sabe faz, quem não sabe ensina.",
    "Quem tarde vier comerá do que trouxer.",
    "Quem te cobre que te descubra.",
    "Quem tem burro e anda a pé mais burro é.",
    "Quem tem capa sempre escapa.",
    "Quem tem cem mas deve cem pouco tem.",
    "Quem nasce torto, tarde ou nunca se endireita.",
    "Quem tudo quer tudo perde.",
    "Quem vai ao mar avia-se em terra.",
    "Quem é vivo sempre aparece.",
    "Querer é poder.",
    "Recordar é viver.",
    "Roma e Pavia não se fez em um dia.",
    "Rei morto, rei posto.",
    "Se em terra entra a gaivota é porque o mar a enxota.",
    "Se sabes o que eu sei, cala-te que eu me calarei.",
    "Santos da casa não fazem milagres.",
    "São mais as vozes que as nozes.",
    "Toda brincadeira tem sempre um pouco de verdade.",
    "Todo o homem tem o seu preço.",
    "Todos os caminhos vão dar a Roma.",
    "Tristezas não pagam dívidas.",
    "Uma mão lava a outra.",
    "Uma desgraça nunca vem só.",
    "Vão-se os anéis e ficam-se os dedos.",
    "Vozes de burro não chegam aos céus.",
    "Zangam-se as comadres, descobrem-se as verdades."
];
sentences = sentences.filter(function(s) {
    return s.split(',').length === 2;
});
sentences = sentences.filter(function(s) {
    return s.split('.').length === 2;
});

function update() {
    var sentence1 = sentences[Math.floor(Math.random()*sentences.length)];
    var sentence2 = sentences[Math.floor(Math.random()*sentences.length)];

    document.getElementById("part1").innerHTML = split(sentence1)[0] + ', ';
    document.getElementById("sentence1").innerHTML = sentence1;
    
    document.getElementById("part2").innerHTML = split(sentence2)[1];
    document.getElementById("sentence2").innerHTML = sentence2;
}

function split(sentence) {
    return sentence.split(',');
}

// setInterval(update, 5000);
