'use strict';

var sentences = [
    "A ambição cerra o coração.",
    "A apressada pergunta, vagarosa resposta.",
    "A ave de rapina não canta.",
    "A barriga não tem fiador.",
    "A boa mão, do Rocim faz cavalo; e a ruim, do Cavalo faz Rocim.",
    "A boca do ambicioso só se fecha com terra da sepultura.",
    "A boda e a baptizado não vás sem ser convidado.",
    "A cada Bacorinho, vem seu S. Martinho (11/11).",
    "A cada boca uma sopa.",
    "A cadela, com pressa, pariu os cachorros cegos.",
    "A campo fraco, Lavrador forte.",
    "A casamento e baptizado, não vás sem ser convidado.",
    "A cavalo dado não se olha o dente.",
    "A chuva de S. João (24/6), bebe o Vinho e come o Pão.",
    "A chuva e o frio, metem a Lebre a caminho.",
    "A conselho amigo, não feches o postigo.",
    "A culpa morreu solteira.",
    "A desgraça não marca encontro.",
    "A encomenda é igual ao cabaz.",
    "A espada e o anel, segundo a mão em que estiverem.",
    "A falta do amigo há-de-se conhecer mas não aborrecer.",
    "A fama longe soa. E mais depressa a má que a boa.",
    "A fome é a melhor cozinheira.",
    "A fome é boa mostarda.",
    "A fome é o melhor tempero.",
    "A fome faz sair o lobo do mato.",
    "A galinha da vizinha é sempre melhor que a minha.",
    "A ganhar se perde e a perder se ganha.",
    "A gosto danado, o doce é amargo.",
    "A ignorância e o vento são do maior atrevimento.",
    "A justiça tarda mas não falha.",
    "A Laranja, de manhã é Ouro, de tarde é Prata, e à noite mata.",
    "A lei é dura, mas é para se cumprir.",
    "A melhor Cozinheira, é a azeiteira.",
    "A Morte abre a porta da Fama e fecha a da Inveja.",
    "A mulher, sem pôr o pé faz pegada.",
    "A necessidade aguça o engenho.",
    "A necessidade não tem lei.",
    "A noite é boa conselheira.",
    "A nuvem passa, mas a chuva fica.",
    "A ocasião faz o ladrão.",
    "A ociosidade é mãe de todos os vícios.",
    "A palavra é de prata e o silêncio é de ouro.",
    "A pedra e a palavra, não se recolhe depois de deitada.",
    "A Pescada de Janeiro, vale um carneiro.",
    "A pintura e a peleja, de longe se veja.",
    "A pobreza não é vileza, nem a riqueza nobreza.",
    "A preguiça é a mãe de todos os vícios.",
    "A preguiça morre à sede, andando a boiar.",
    "A pressa é inimiga da perfeição.",
    "A primeira, qualquer cai. À segunda cai quem quer.",
    "A quem do seu foi mau despenseiro, não fies o teu dinheiro.",
    "A quem tudo quer saber, nada se lhe diz.",
    "A razão e a verdade fogem quando ouvem disputas.",
    "A rir se corrigem os costumes.",
    "A roupa suja lava-se em casa.",
    "A união faz a força.",
    "A vaidade é o espelho dos tolos.",
    "A valentia com os fracos, só cobardia revela.",
    "A ventre farto o mel amarga.",
    "A verdade é como o azeite: Vem sempre ao de cima.",
    "A vozes loucas, orelhas moucas.",
    "Abril frio e molhado, enche o celeiro e farta o gado.",
    "Abril, Abril, está cheio o covil.",
    "Agosto tem a culpa, e Setembro leva a fruta.",
    "Água de Fevereiro, mata o Onzeneiro.",
    "Água de Julho, no rio não faz barulho.",
    "Água detida é má para a bebida.",
    "Água e vento são meio sustento.",
    "Água mole em pedra dura, tando dá até que fura.",
    "Águas da Ascensão, das palhas fazem Grão.",
    "Águas passadas não movem Moinhos.",
    "Águas verdadeiras, por S. Mateus as primeiras.",
    "Aí por Sant'ana, limpa a pragana.",
    "Ainda que mude a pele a Raposa, seu natural desponja.",
    "Albarda-se o burro à vontade do dono.",
    "Almoço cedo, faz carne e sebo; almoço tarde, nem sebo nem carne.",
    "Alto mar e não de vento, não promete seguro o tempo.",
    "Amigo deligente, é melhor que parente.",
    "Amigo disfarçado, inimigo dobrado.",
    "Amigo que não presta e faca que não corta: que se percam, pouco importa.",
    "Amigo verdadeiro vale mais do que dinheiro.",
    "Amigo, vinho e azeite o mais antigo.",
    "Amigos, amigos, negócios à parte.",
    "Amor com amor se paga.",
    "Amor de pais não há jamais.",
    "Amor querido, amor batido.",
    "Amores arrufados, amores dobrados.",
    "Ande o frio por onde andar, no Natal cá vem parar.",
    "Ande por onde andar o Verão, há-de vir no S. João.",
    "Ano de nevão, ano de pão.",
    "Ano de neve, paga o que deve.",
    "Antes caia do cú do que do alforge.",
    "Antes cegues que mal vejas.",
    "Antes martelo que bigorna.",
    "Antes mau ano que mau vizinho.",
    "Antes minha face com fome amarela, que vergonha nela.",
    "Antes que te cases, vê o que fazes.",
    "Antes quebrar que torcer.",
    "Antes quero Asno que me leve, que Cavalo que me derrube.",
    "Ao arrendar cantar e ao pagar chorar.",
    "Ao bebado e ao tolo, dá-se o caminho todo.",
    "Ao bom amigo, com teu pão e teu vinho.",
    "Ao bom pagador não dói o penhor.",
    "Ao Diabo e à mulher nunca falta que fazer.",
    "Ao Fevereiro e ao rapaz, perdoa tudo quanto faz.",
    "Ao homem de esforço a fortuna lhe põe ombro.",
    "Ao homem ousado a fortuna dá a mão.",
    "Ao menino e ao borracho põe Deus a mão por baixo.",
    "Ao pé do pano é que se talha a obra.",
    "Ao quinto dia verás que mês terás.",
    "Ao rico mil amigos se deparam, ao pobre seus irmãos o desamparam.",
    "Ao rico não devas e ao pobre não peças.",
    "Ao rico não faltes, ao pobre não prometas.",
    "Apanha com o cajado quem se mete onde não é chamado.",
    "Apanha-se mais depressa um mentiroso do que um coxo.",
    "Apanham-se mais moscas com mel do que com fel.",
    "Apressado come cru.",
    "Aproveite Fevereiro quem folgou em Janeiro.",
    "Aquele que me tira do perigo, é meu amigo.",
    "Aquilo que sabe bem, ou faz mal ou é pecado.",
    "Arco de teixo duro de armar e fraco para disparar.",
    "Arco sempre armado, ou frouxo ou quebrado.",
    "Arrenda a vinha e o pomar se os queres desgraçar.",
    "As aparências iludem.",
    "As boas contas fazem os bons amigos.",
    "As cadelas apressadas parem cães tortos.",
    "As favas, Maio as dá, Maio as leva.",
    "As obras falam, as palavras calam.",
    "As palavras são como as cerejas, vêm umas atrás das outras.",
    "As palavras voam, a escrita fica.",
    "As paredes têm ouvidos.",
    "As sopas e os amores, os primeiros são os melhores.",
    "Às vezes não se respeita o burro, mas a argola a que ele está amarrado.",
    "Assim como vires o tempo de Santa Luzia ao Natal, assim estará o ano mês a mês até final.",
    "Até ao lavar dos cestos é vindima.",
    "Até ao Natal um saltinho de pardal.",
    "Até S. Pedro abre rego e fecha rego.",
    "Até S. Pedro tem a vinha medo.",
    "Atrás de mim virá, quem de mim bem dirá.",
    "Ave que canta demais não sabe fazer o ninho.",
    "Ave só não faz ninho.",
    "Azeite de cima, mel do fundo e vinho do meio."
];
sentences = sentences.filter(function(s) {
    return s.split(',').length === 2;
});

function update() {
    var sentence1 = sentences[Math.floor(Math.random()*sentences.length)];
    var sentence2 = sentences[Math.floor(Math.random()*sentences.length)];

    document.getElementById("part1").innerHTML = sentence1.split(',')[0] + ', ';
    document.getElementById("sentence1").innerHTML = sentence1;
    
    document.getElementById("part2").innerHTML = sentence2.split(',')[1];
    document.getElementById("sentence2").innerHTML = sentence2;
}



// setInterval(update, 5000);
